#!/usr/bin/env zsh

pushd $DOTFILES

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Cleaning up files from $folder"
    stow -D $folder

    # Find all files within the folder
    find $folder -type f | while read file; do
        # Determine the target file location in the home directory
        target="$HOME/${file#$folder/}"

        # Check if the target file exists and move it
        if [ -e "$target" ]; then
            timestamp=$(date "+%Y_%m_%d_%H:%M")

            # Define the backup file name with timestamp
            backup="${target}_${timestamp}.bak"

            echo "Moving $target to $backup"
            mv "$target" "$backup"
        fi
    done
done

popd
