#!/usr/bin/env zsh

OS=$(uname -s | tr '[:upper:]' '[:lower:]')

case "$OS" in
    linux)
        STOW_FOLDERS="zsh-linux,i3,nvim,tmux-linux,bin,code-linux,polybar"
        ;;
    darwin)
        STOW_FOLDERS="code-mac,zsh-mac,tmux-mac,bin,aerospace"
        ;;
    *)
        echo "Unsupported OS: $OS"
        exit 1
        ;;
esac

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi

usage() {
    echo "Usage: $0 [--install | --clean-env]"
    exit 1
}

if [[ $# -eq 0 ]]; then
    usage
fi

case $1 in
--install)
    STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
    ;;
--clean-env)
    STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/clean-env
    ;;
*)
    usage
    ;;
esac
